name: Deploy to Cloudtype

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.13.2

      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --store-dir ~/.pnpm-store

      - name: Run unit tests
        run: pnpm test

  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push job-crawler
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/job-crawler.dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/job-crawler:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push web-service
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/web-service.dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/web-service:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Install Cloudtype CLI
        run: npm install -g @cloudtype/cli

      - name: Deploy job-crawler to Cloudtype
        run: |
          cloudtype deploy \
            --token ${{ secrets.CLOUDTYPE_TOKEN }} \
            --project ${{ secrets.CLOUDTYPE_PROJECT_ID }} \
            --service job-crawler \
            --image ${{ secrets.DOCKERHUB_USERNAME }}/job-crawler:latest

      - name: Deploy web-service to Cloudtype
        run: |
          cloudtype deploy \
            --token ${{ secrets.CLOUDTYPE_TOKEN }} \
            --project ${{ secrets.CLOUDTYPE_PROJECT_ID }} \
            --service web-service \
            --image ${{ secrets.DOCKERHUB_USERNAME }}/web-service:latest
